# Generated by Django 5.1.4 on 2025-02-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ice_cream_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='anonymous', max_length=100)),
                ('comment', models.TextField(max_length=160)),
                ('rating', models.IntegerField(default=3)),
                ('captcha_result', models.CharField(max_length=10)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
