# Generated by Django 5.1.4 on 2025-02-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ice_cream_shop', '0002_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='date_submitted',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='captcha_result',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
